### ISSUE TITLE
Feature Request: Map Run/stop key to the TAB key on USB keyboards.

### ISSUE THREAD

**Issue by mbwum73** [GideonZ/ultimate_releases#17]
When I attach a (wireless) USB keyboard to the Ultimate 64 alomost all keys work just fine.
However the Run/Stop key is mapped to the pause/break key on the USB keyboard.
Unfortunately many keyboards, especially the small ones, do not have the pause/break key anymore.
Can you please also map the Run/Stop key to the TAB key on the USB keyboard? All keyboards have this key and as for as I can tell it's not being mapped to any key at all yet in the Ultimate 64. It would solve the problem for keyboards without a pause/break key.

Because many games require run.stop to start the game I think mapping that key is essential.

I hope you can add this feature Gideon. I love my Ultimate 64!

**Comment by mbwum73** [comment]
Just to add to my request. Esc would be even better for the run/stop key.

**Comment by GideonZ** [comment]
Implemented in f8dc6484.
*PLEASE ADD ISSUES TO THE 1541ULTIMATE REPOSITORY!*
