### ISSUE TITLE
Telnet closes when Mounting an image

### ISSUE THREAD

**Issue by TomCat666** [GideonZ/ultimate_releases#22]
In version 3.10a when I telnet to the 1541u2+ everything works fine, but for some reason when I mount the image over the telnet the telnet window closes (the connection is interrupted) every time. While "Mount and Run" a file keeps the telnet window open.

**Comment by Grrrolf** [comment]
Duplicate of [250](https://github.com/GideonZ/1541ultimate/issues/250).
Please use this [repository](https://github.com/GideonZ/1541ultimate/issues) repo for filing issues.

**Comment by TomCat666** [comment]
Will do. thank you. Closing this one.
