### ISSUE TITLE
Ultimate-II Plus-L / Telnet connection error after Mounting Disk.

### ISSUE THREAD

**Issue by natrixu** [GideonZ/ultimate_releases#33]
Firmware 3.10e and 3.10f

When connecting to UltimateII+L via TELNET after selecting Mount Disk in the terminal, the connection is immediately closed after loading the disk image in C64 - "closed with error: connection reset by peer".
However, Run Disk works fine and the TELNET connection is still active.

**Comment by Grrrolf** [comment]
This is expected behaviour. This behaviour was different in firmware versions < 3.10. You can change this behavior in the user interface settings (if i remember correctly).

**Comment by Grrrolf** [comment]
> Now I know what needs to be done. In the "Drive Settings" there is an option "Leave Menu on Mount" which must be turned off. Unfortunately, it was not obvious to me that the drives settings affect the connection via TELNET.

I can imagine that that is not obvious. I'm glad that it's a configuration option now and you found the actual location! 

If your issue has been solved, can you please close the ticket? I cannot do that, only you and Gideon can.
