### ISSUE TITLE
Martech loaders crash (Ultimate 64 - Firmware V3.10a)

### ISSUE THREAD

**Issue by RichardTND** [GideonZ/ultimate_releases#34]
There appears to be a major issue attempting to load games that use the IRQ music playing version of the Martech tape loader system. 
The Legend of Tarzan, Nemesis The Warlock, and Zarjaz crashes instead of plays loading music and display loading bitmap. The digital tape files (TAP) all work in VICE, and possibly on a real C64. I don't think those loaders have any anti-peripheral protection either. 

Edit: I just got a notification that he's aware of the problem. Possibly something to do with the loader's depacker routines.

**Comment by johnlivdahl** [comment]
This is the wrong git spot to report FW issue.  
Here is a link to a duplicate issue with a patched Tarzan loader https://github.com/GideonZ/1541ultimate/issues/206
