### ISSUE TITLE
Ulticopy hangs reading a disc on 3.11a

### ISSUE THREAD

**Issue by mbrukner** [GideonZ/ultimate_releases#42]
I have tried different C64s, both with confirmed good CIAs and two different disk drives. Ulticopy just hangs when it would normally start reading the disk. Only way out at that point is to turn off the computer.

**Comment by Grrrolf** [comment]
This is the wrong repo for filing bug reports.
This is the correct repository: https://github.com/GideonZ/1541ultimate/issues

Try using the workaround mentioned in this ticket: https://github.com/GideonZ/1541ultimate/issues/397

**Comment by mbrukner** [comment]
Thanks @Grrrolf, will try that!
